theme = "dark_plus" # github_dark vesper gruvbox_dark_soft gruvbox_light_soft everblush

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
select = "underline"
