#!/bin/bash

# -p Создать все директории, которые указаны внутри пути. Если какая-либо директория существует, то предупреждение об этом не выводится.
mkdir -p $HOME/.norg
mkdir -p $HOME/.wallpapers
mkdir -p $HOME/.programs
mkdir -p $HOME/.scripts
